### ISSUE TITLE
Error when submitting - TEST

### ISSUE THREAD

**Issue by Dara-K** [topcoderinc/cab#42]
Every time after submitting, an error appears on the new site instead of the confirmation. The message displayed is "Got an error? Get a cake!"

**Comment by hokienick** [comment]
I do enjoy cake!

**Comment by Dara-K** [comment]
Why did you close this Captain?

**Comment by cwdcwd** [comment]
![image](https://cloud.githubusercontent.com/assets/1504607/22040913/c36acec0-dcd2-11e6-979a-de391bad6c51.png)
