### ISSUE TITLE
Send reminders for all SRMs and set the dates with anticipation

### ISSUE THREAD

**Issue by ltaravilse** [topcoderinc/cab#45]
Nowadays we don't receive reminder emails for all SRMs.

You can send reminders for all SRMs and/or create a Calendar in Google Calendar with all SRMs so people can configure the calendar to send automatic reminders before SRMs.

Also it would be nice to have SRM's dates some time before. As an example, today, on January, 18th, there are not SRMs for February on https://www.topcoder.com/community/events/

**Comment by tcNickolas** [comment]
The same applies to Marathon matches (btw, this issue tracker needs a label for them). I got a reminder for MM 91 but didn't get one for MM 92.

**Comment by rashid-sial** [comment]
hey @ltaravilse, please see my feedback below:

Nowadays we don't receive reminder emails for all SRMs.
> Looks like you're not subscribed to them. Do you want me to add this for you?

You can send reminders for all SRMs and/or create a Calendar in Google Calendar with all SRMs so people can configure the calendar to send automatic reminders before SRMs.
> This is a great idea.

Also it would be nice to have SRM's dates some time before. As an example, today, on January, 18th, there are not SRMs for February on https://www.topcoder.com/community/events/
> Will look into this.

**Comment by rashid-sial** [comment]
@tcNickolas, whats your handle?

**Comment by tcNickolas** [comment]
@rsial2 Nickolas

**Comment by rashid-sial** [comment]
@tcNickolas looks like you're getting the SRM reminders (I checked Mailchimp, our provider). But for the MM's themselves, you have to sign up on the pre-registration microsites. Can you create a new issue that describes your request: i.e that we need to send out MM reminders without having someone sign up on the pre-registration microsites.

**Comment by tcNickolas** [comment]
@rsial2 Yes, I'm receiving SRM reminders. For MMs, I'm talking about for-fun MMs, not the sponsored ones. Like I said, I got a reminder for MM 91 without signing up at any microsite. Opened issue #56

**Comment by ltaravilse** [comment]
https://www.topcoder.com/community/events/ this is the calendar but it has MM and other contests on it too.

**Comment by hokienick** [comment]
*CAB MEETING*

Jessie will follow up with Harshit to investigate the mail client and see if anything can be done.  She will also talk to Tim about updating the calendar sooner.

Notifications 1 week and 1 day before the SRM.
