### ISSUE TITLE
Make example code available for MM contests

### ISSUE THREAD

**Issue by ltaravilse** [topcoderinc/cab#48]
It would be good, specially for newcomers, to give a sample code for every Marathon Match, in every available language. For example, in C++ a .cpp that creates a class instance, calls the public method that needs to be implemented, and include the .h that can be the same file that is submitted for the Marathon Match. The same can be done in Java and any other available language.

**Comment by tcNickolas** [comment]
We've been doing this since the first round of TCO16 I think :-)

**Comment by rashid-sial** [comment]
@ltaravilse can you clarify?

**Comment by tcNickolas** [comment]
@rsial2 Here is what we're doing currently: if you check the statement for the latest MM 92 https://community.topcoder.com/longcontest/?module=ViewProblemStatement&rd=16857&pm=14485, it has a link to tester manual http://www.topcoder.com/contest/problem/Lighting/manual.html , which in turn has links to example solutions in different languages.

**Comment by rashid-sial** [comment]
Ok got it, thanks!

**Comment by rashid-sial** [comment]
Closing this issue since there's currently a solution.
