### ISSUE TITLE
NDA explanation for an average member?

### ISSUE THREAD

**Issue by birdofpreyru** [topcoderinc/cab#53]
We all sign NDA to participate in challenges. They are written in a fancy legal language, and contain many letters, so, I believe, most members never read/understand them, and just take the message `It is fine to keep your mouth shut about what you are doing at TopCoder`.

I'd like to see a more average-human explanation of NDAs (and probably other members too)? Specifically, I'm interested whether, and when we can include basic info about TC projects in our CVs? Can we share in our Facebooks something like

> Hey, look what at http://www.brilliantcareerlab.org/! Fancy site, produced by TopCoder, and I have actively participated in its development!

I believe, this matter is project dependent, can we somehow mark the challenges/projects, which members can tell about? It might be beneficial for TC, as a free advertisements => more people get to know about it, more people interested to try, more projects we can handle.

**Comment by hokienick** [comment]
Remember your label @birdofpreyru ! 😸

**Comment by vic-georgiev** [comment]
I like this! While ago I've glanced over several articles, and there was a website (can't find it yet) for outlining important TOC and NDA from various websites. I was thinking that maybe an iconic system similar to Creative Commons or laundry label would work nice to depict the NDA/TOC for the challenge, and we can translate the details underneath
![screen shot](https://cloud.githubusercontent.com/assets/8484061/22531895/c7e16154-e898-11e6-902c-691813b1dece.png)

**Comment by callmekatootie** [comment]
Is this the website you are talking about @vic-topcoder - https://tldrlegal.com/

An example for Youtube's TOS - https://tldrlegal.com/license/youtube-terms-of-service

**Comment by vic-georgiev** [comment]
@callmekatootie yes indeed! Thanks for finding it. It is important to be able to interpret what's written, but also keep the full legality of the TOC/NDA, etc. We have to check the issue with TC/Wipro legal office though, as to make sure everything is ok if we take such an approach.

**Comment by hokienick** [comment]
Had conversation with @mcards13 06/29 and he will be discussing with his team if Qualtrics is the way to proceed with this.  There are many other factors that need to be accounted for as well.  The plan is to have a first draft of a plan to discuss with CAB by end of July.

**Comment by hokienick** [comment]
06/28 - I will bring this to our internal content person to see if she can take a pass at two of the most common agreements (General Terms of Service and NDA) and put them in laments terms.

Once this is completed, we will bring this to our legal department to assure we are correct in our translation.

This will then be posted in our Help Center along with creating question mark icons next to the associated link on the Challenge Details page.

**Comment by hokienick** [comment]
This was brought to the attention of our legal department and they said that we will not be able to accomplish this.  They just do not want any confusion no matter how small on what is already written and what would be conveyed.  

Putting this in the "Not Happening" column.
