### ISSUE TITLE
Send email reminders for regular (non-sponsored) Marathon Matches

### ISSUE THREAD

**Issue by tcNickolas** [topcoderinc/cab#56]
Branching out from #45 : we need to make sure Marathon email reminders are sent out for all Marathons without having members sign up at any microsites specific to a match. For example, I (Nickolas) received a reminder for MM 91 but not for MM 92.

**Comment by rashid-sial** [comment]
Thanks, I'll raise this with our product development team.

CC @hokienick

**Comment by tcNickolas** [comment]
@rsial2 @hokienick You can start with MM 93 - we've put it on the calendar already and it is scheduled to start on March 1st, so an email reminder about it some time soon would be awesome.

**Comment by rashid-sial** [comment]
I don't think it'll happen in time for MM 93 - or even if it'll happen. It still needs to get approved by our prod dev team.

**Comment by tcNickolas** [comment]
There shouldn't be any difference for fun MMs vs SRMs reminders, they go out to the same audience, just the wording is different.

**Comment by tcNickolas** [comment]
@rsial2 @hokienick Nice job with email reminders for MM 93! Let's see whether this improves the participation levels (I very much hope so!)

**Comment by rashid-sial** [comment]
Thanks, gonna close this ticket.
