### ISSUE TITLE
Make virtual-participation available

### ISSUE THREAD

**Issue by ltaravilse** [topcoderinc/cab#60]
Virtual participation (be able to "compete" on a SRM after it ended with the live scoreboard merged with the real contest scoreboard) may be a good idea to attract people to TopCoder.

**Comment by hokienick** [comment]
*CAB MEETING*

Would like a feature where members could participate in the SRM after it has completed (unrated) but would be like participating in real time (see where they would have fallen on the leaderboard).

**Comment by rashid-sial** [comment]
thanks @ltaravilse, I'll raise this with our product development team.

CC @hokienick

**Comment by hokienick** [comment]
No bandwidth to do this and not something that will be putting on the roadmap.
