### ISSUE TITLE
Registering after checkpoint

### ISSUE THREAD

**Issue by f0rc0d3r** [topcoderinc/cab#62]
Is confusing to be able to register after checkpoint which means that you will not longer be able to submit. For example MM has the same end date to register and to submit. In design contest the end date to register should be the same date of checkpoint and if there is no checkpoint the same date as final submission date.

This issue affects some places:
- In the dashboard: 
For example a contest can show "next phase: registering, 10 days" because this phase comes before checkpoint in the timeline, but maybe you have 4 days for checkpoint and you don't see this.
- In the contest search page - at a glance if you see "time left" for new contest you can think and plan for more days than you really have to submit
- In the challenge page - the same (see the attached image): the contest says that I have 10 days to register but what I really want to see is time left for checkpoint which is less.

**Comment by f0rc0d3r** [comment]
![timeleft](https://cloud.githubusercontent.com/assets/7061985/23036922/dd743d8c-f484-11e6-8537-47a6d424c871.png)

**Comment by birdofpreyru** [comment]
Challenge listing page will be replaced soon, as you heard.

In the Dashboard and at the challenge Specs page I can arrage it to be changed soon, just need understand better what should be done. Are these points valid for all challenges in design track, or only to some of them? Does it make sense to disabled registration after the checkpoint (registration is not only about submitting, but also about access to forums, thus following an on-going challenge)?

**Comment by hokienick** [comment]
Tony has fixed this!
