### ISSUE TITLE
Send wiki pages to main site

### ISSUE THREAD

**Issue by ltaravilse** [topcoderinc/cab#67]
There are a lot of wiki pages (like how to be a problemsetter, editorials, tutorials) that is hard to access from the new website if you don't search for them with a search engine. It would be nice to make them more accessible for everyone.

**Comment by ltaravilse** [comment]
https://apps.topcoder.com/wiki/display/tc/Write+Problems+for+TopCoder

Here's an example

**Comment by ltaravilse** [comment]
https://www.topcoder.com/community/data-science/data-science-tutorials/ This is also hard to find

**Comment by rashid-sial** [comment]
Rash will work on this. Will be completed by 04/14.
