### ISSUE TITLE
Make recent Marathon matches available for practice

### ISSUE THREAD

**Issue by tcNickolas** [topcoderinc/cab#68]
The most modern match available in https://community.topcoder.com/longcontest/?module=ViewPractice is LawnMoving which dates back to 2015 (over a year old). We had a lot of matches since than :-)

**Comment by vic-georgiev** [comment]
Yeah, we have to update the MM and SRMs be visible on the topcoder page and list all data. We're working on the new challenge listing pages, and marathon matches should be there, as well as SRMs. Also, in the next several days we're starting redesign concept challenges for the details pages.

**Comment by hokienick** [comment]
Will have to bring in Tim to see how this is currently being executed.

**Comment by hokienick** [comment]
Tim says that he will be creating some practice MMs from recent ones and will put them up for practice after they end from here on out.

Putting this "In Progress" until it actually goes into effect.

**Comment by hokienick** [comment]
Tim aims to have this available by Tuesday July 18th.

**Comment by hokienick** [comment]
Tim has now made the 3 TCO17 marathons for this year available in practice.  He will be adding other fun marathons soon, but these were the most popular.

**Comment by tcNickolas** [comment]
It would help a lot to have more descriptive match titles: "TCO17 Round 1" instead of just "Round 1"
