### ISSUE TITLE
FAQ about Python in Arena

### ISSUE THREAD

**Issue by hokienick** [topcoderinc/cab#73]
_Message from member (ccooper):_

> Hi,
> 
> I participated in the TopCoder Open 2017 Regional Event in Austin over the weekend. It was a fun time!
> 
> This was the first time that I had participated in a TopCoder match in quite some time. Ages ago when I first participated in TopCoder matches (~2002) I used Java. In recent years I have moved to using Python for most of my software development work. I some how knew that TopCoder now supports Python, but didn't know if it is Python 2 or 3. If I had previously competed in TopCoder using Python it has only been once or twice, and I had forgotten the answer. In any case, I spent a good 10 minutes during the registration period searching Google, the TopCoder help pages, etc. trying to figure out if TopCoder supports Python 2 or Python 3. Despite this being a very important distinction when working in Python, I couldn't find any reference to the answer except for an old and potentially outdated forum discussion. I figured out the answer is Python 2 once the contest started, but I wasted valuable contest time trying to figure out the answer and reconfiguring my local IDE accordingly.
> 
> Given the above, it would be great if this could be made more clear. Maybe this piece of information belongs in a FAQ, hopefully to be indexed by Google. Or, it would be nice when picking Python in the code editor if the label actually said "Python 2" instead of just ambiguously saying "Python".
> 
> If this is documented somewhere, I suppose I'd be interested to know where. However, I don't have any confidence that someone else who is new to TopCoder or new to using Python with TopCoder would have more success finding the answer.
> 
> -- Chris

**Comment by tcNickolas** [comment]
I was asked this same question today about SRM environment in general, not limited to Python. https://community.topcoder.com/tc?module=Static&d1=help&d2=generalFaq is very old and I hope the things have been updated since then, but it needs to be documented. For Marathons there is at least something at https://apps.topcoder.com/wiki/display/tc/Processing+server+specifications+(AWS)

And even this old documentation is very hard to find, I couldn't find it other than using this fixed link

**Comment by ThomasKranitsas** [comment]
@tcNickolas documentation from the legacy site will be ported in https://help.topcoder.com
You can see that some documentations have already been ported here: https://help.topcoder.com/hc/en-us#DATA SCIENCE

**Comment by hokienick** [comment]
Tim K should be back from paternity leave week of 07/03 and I will contact him about this.

**Comment by hokienick** [comment]
Tim to write help doc surrounding this topic by end of next week.

**Comment by hokienick** [comment]
Tim has provided us with the fact that Python version 2.6.6 is the one being used.  Added to the Help Center here: https://help.topcoder.com/hc/en-us/articles/230881408-Data-Science-Challenge-Types

**Comment by tcNickolas** [comment]
@hokienick The link you've provided https://help.topcoder.com/hc/en-us/articles/230881408-Data-Science-Challenge-Types has exactly nothing about the version of Python used, or version of any language used for that matter

**Comment by burnpanck** [comment]
Yep, documentation seems to be *very much* out of date at TopCoder...
