### ISSUE TITLE
Additional stock icon resource

### ISSUE THREAD

**Issue by panjikharisma** [topcoderinc/cab#76]
The addition of icons8 in stock icon resource is very helpful for designer. However there's some limitation as icons8 icons are only developed by a single team. So I suggest to include an icon aggregator site with a subscription plan (same with icons8) to be used in the future development.

Basically these are the 3 most famous platform for icon designer (afaik) :
- Flaticon (flaticon.com - $9.99/month)
- The Noun Project (thenounproject.com - $ 9.99/month)
- Icon Finder (iconfinder.com - $29/month )

If I can only choose one, I personally recommend the addition of flaticon for it's price & versatility of it's colored icons.

Lastly, there is also a suggestion for a single team resource by yoki NucleoApp (nucleoapp.com), it has a big very professional set with the same style used (which is very nice). The pricing of NucleoApp is $49/year.

**Comment by Ravijune** [comment]
Thank you for the suggestion Panji. I would recommend flaticon.com too as it has more varieties/styles. 
Let's wait for the other members response too on this and finalise by the next cab meeting with our team.

**Comment by hokienick** [comment]
birdofpreyru will be contacted by Ravi to get this change fixed.
