### ISSUE TITLE
Unable to find upcoming contests

### ISSUE THREAD

**Issue by f0rc0d3r** [topcoderinc/cab#77]
Members are used to look often at new contest listing pages to be prepared, schedule time... right now members are unable to look for new contests. The new challenges listing page has some filters but none of them involves the possibility to see only upcoming challenges.

Is this a new rule or is this a bug to be solved? Maybe something forgotten?

Maybe this is caused by secondary issues:

- When the page is loaded and we see "All Challenges", clicking "View more challenges" in the bottom section (Open for review) leads to a different page: https://www.topcoder.com/review/review-opportunities/

- Filters are not buddies... we cannot use some combination of filters and they have no memory. (For example each time we click a direct filter (All Challenges, My Challenges...) we lose the top filtering by Design/Development/Data Science

Or maybe there are no future contests in the system and that's why we cannot see them...

**In any case it will be helpful to be able to see upcoming contests and to have a direct filter for this.**

i think this is really important for competitors, to know in advance when a contest will start, specially for bug hunts or first to finish so this should be treated with priority...

**Comment by hokienick** [comment]
Upcoming Challenges function has been removed and all other bugs about the filter has been resolved, most likely thanks to DaraK for referencing this issue!
