### ISSUE TITLE
A new Business page 

### ISSUE THREAD

**Issue by Sande3p** [topcoderinc/cab#79]
Many new members get confused when visiting topcoder.com ref: https://apps.topcoder.com/forums/?module=Thread&threadID=900835&start=0
![image](https://user-images.githubusercontent.com/3652329/28038583-0e82bf1a-65dd-11e7-9e1e-de58b6e2c2b4.png)

The same can be true for TopCoders future/returning clients.  Presently reaching this page http://crowdsourcing.topcoder.com/piqued_by_crowdsourcing  seems to be confusing.

Maybe we should add new `Business` page may have URL business.topcoder.com.
- somewhat like https://www.google.co.in/services/?fg=1#?modal_active=none
- that can be directly accessed from the homepage

**Comment by hokienick** [comment]
We are actively working on relaunching the page you are talking about.  You should see it updated end of feb / early march.
