### ISSUE TITLE
Profile Info Is Cut in 50% cases

### ISSUE THREAD

**Issue by agorbunovs** [topcoderinc/cab#80]
As a user of topcoder.com, I want to see my and other competitors' competition/rating history.
However, if I open a member's profile by clicking on his handle on the forums, or in the competition standings page, I got to a page like this: [https://www.topcoder.com/members/walrus71/](https://www.topcoder.com/members/walrus71/). In some cases it shows me ratings, in other cases it does not. After some Ctrl+F5 hits I can get the profile with ratings and links to competition history.

![profile1](https://user-images.githubusercontent.com/2240632/29189815-959920d8-7e20-11e7-9a22-2b75cfd75e98.png)
![profile2](https://user-images.githubusercontent.com/2240632/29189884-c99da20a-7e20-11e7-94d6-44485126f45c.png)

**Comment by ThomasKranitsas** [comment]
Hi @agorbunovs!

The whole Topcoder website is currently being re-developed using the latest best practices so issues like this will be fixed.

Thank you for mention it though.
@birdofpreyru fyi

BTW It is better to submit such bugs [in this repo](https://github.com/appirio-tech/topcoder-app/issues)

I'll close this issues as it doesn't belong here 🙂 
@hokienick fyi

**Comment by agorbunovs** [comment]
You are right, did not notice I was on a different repo.

**Comment by vic-georgiev** [comment]
Hey @agorbunovs, thanks for the feedback. We would like to rethink the profile design at some point and putting the stats and winnings back on focus would be nice. We heard this kind of feedback from many other community members.

Just of curiosity: if you have the ability to preview a member profile on hover — a tooltips like on Facebook or Twitter — what do you want to see and why? What is the most important information for a member that you want to learn and why?

Thanks,
Vic

**Comment by agorbunovs** [comment]
First, I'm glad to hear the website is being developed.

Answering your question, it would be the member quote for me. They are not visible now and are kind of replaced with "bio" section in profile now. Also, "Member since <month>/<year>" would be good. Maybe forum post amount. Other members may wish to see ratings there, I guess.

But in general, my opinion is that adding new stuff should happen after the old goodies are implemented in the new version ;).

**Comment by agorbunovs** [comment]
Actually there was a plenty of goodies in the v1 website (very old red-grey design). Would be great if these goodies are back!

**Comment by vic-georgiev** [comment]
Thank you @agorbunovs, we're going to take your feedback into consideration. Yes, there are a lot of things that changed with time, and we realize we need to have some of the lost items back (like badges).

**Comment by ThomasKranitsas** [comment]
@vic-topcoder 
>Just of curiosity: if you have the ability to preview a member profile on hover — a tooltips like on Facebook or Twitter — what do you want to see and why? What is the most important information for a member that you want to learn and why?

The best feature would be to show the current time in member's local timezone.

**Comment by lstkz** [comment]
@ThomasKranitsas 
Why did you close this issue instantly? At least you could move it to the another repo...

@vic-topcoder 
It's not about the current design. There is a bug, and tracks are not displayed.
I have the same bug very often, and other members reported it too.

**Comment by ThomasKranitsas** [comment]
@lsentkiewicz my bad... I posted the link to the repo where members should post such bugs but I didn't check if this ticket was created there.
